---
title: "netradiation_calcs"
author: "Erika Lee"
date: "2024-07-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lterdatasampler)
library(dplyr)
library(ggplot2)
library(readr)
library(readxl)
library(lubridate)
library(plotly)
library(openxlsx)
library(plotly)
library(rstatix)
library(htmlwidgets)
library(RColorBrewer)
library(patchwork)
#package for scientific notation of numbers
library(scales)

setwd("/Volumes/wcnr-network/Research/Kampf/Private/field_data")
```

# Calling in Data

```{r}
#calling in weather station data from n-drive
##persistent zone
persb_wx_15min <- read_excel("nsf/pers_burned/pers_burned_wx_15min_r.xlsx")

persub_wx_15min <- read_excel("nsf/pers_unburned/pers_unburned_wx_15min_composite.xlsx")

##transitional
transb_wx_15min <- read_excel("nsf/trans_burned/trans_burned_wx_15min_r.xlsx")

transub_wx_15min <- read_excel("nsf/trans_unburned/trans_unburned_wx_15min_r.xlsx")
```

```{r}
#calling in tree temp data from n-drive
## burned
pers_b_aspects <- read_excel("nsf/105E_pers_burned/105E_pers_b_aspects.xlsx") %>%
  mutate(datetime = ymd_hms(datetime))

trans_b_aspects <- read_excel("nsf/105E_trans_burned/105E_trans_b_aspects.xlsx") %>%
  mutate(datetime = ymd_hms(datetime))

##unburned
pers_ub_aspects <- read_excel("nsf/105E_pers_unburned/105E_pers_ub_aspects.xlsx") %>%
  mutate(datetime = ymd_hms(datetime))

trans_ub_aspects <- read_excel("nsf/105E_trans_unburned/105E_trans_ub_aspects.xlsx") %>%
  mutate(datetime = ymd_hms(datetime))
```

```{r}
#setting a consistent timeframe for all tree temp data for all burned/unburned zones
##has to start at 2024-02-02 due to errors in data at transitional burned site

#tree temp dataframes
start_time <- ymd_hms("2024-02-02 00:00:00")
end_time <- ymd_hms("2024-05-24 00:00:00")

filtered_pers_b_aspects <- pers_b_aspects %>%
  filter(datetime >= start_time & datetime <= end_time) %>%
  #adding in column for site name, for when combining dataframes
  mutate(site = "pers_burned") %>%
  mutate(tree_circ_m = '')

filtered_pers_ub_aspects <- pers_ub_aspects %>%
  filter(datetime >= start_time & datetime <= end_time) %>%
  mutate(site = "pers_unburned")

filtered_trans_b_aspects <- trans_b_aspects %>%
  filter(datetime >= start_time & datetime <= end_time) %>%
  mutate(site = "trans_burned")

filtered_trans_ub_aspects <- trans_ub_aspects %>%
  filter(datetime >= start_time & datetime <= end_time) %>%
  mutate(site = "trans_unburned")
```

```{r}
#creating one compiled dataframe that has all tree temps in it

all_treetemps <- bind_rows(filtered_pers_b_aspects, filtered_pers_ub_aspects, filtered_trans_b_aspects, filtered_trans_ub_aspects)
```

# RL for trees Calculations

Create a 15 min Rl(in) calculation for trees based on the tree temp

```{r}
# Constants
stefan_boltzmann_constant <- 5.67e-8
emissivity <- 0.97
#wedll depth and circumference are in meters
welldepth <- 1
circumference <- 0.40
#average circumference of a lodgepole is ~ 16 inches = 0.40 meters
#picking an average unit depth for well depth of 1 meter

#constant for m2 
m2 = welldepth*circumference

# Define the time interval (15 minutes in seconds)
time_interval_seconds <- 15 * 60

# Calculate incoming longwave radiation and add to dataframe
all_treetemps <- all_treetemps %>%
  #add a date column for calculations later
  mutate(date = as_date(datetime)) %>%
  mutate(
    temp_k= temp + 273.15, # Convert temperature to Kelvin
    tree_RL_in = emissivity * stefan_boltzmann_constant * (temp_k^4) # Calculate longwave radiation
  ) %>%
#the RL_in units are W/m2, the m2 component is 
  #calculating watz (W)
  #W is = to J/s
  mutate(W = tree_RL_in*m2) %>%
  # Convert instantaneous power (W) to energy (J) for each 15-minute interval
  mutate(energy_J = W * time_interval_seconds)
```

```{r}
# Aggregate energy (J) to get daily total energy in Joules
daily_energy_MJ <- all_treetemps %>%
  group_by(date, tree_name, site, aspect) %>%
  summarize(daily_energy_J = sum(energy_J, na.rm = TRUE)) %>%
  ungroup() %>%
  # Removing charred and uncharred aspects
  filter(aspect %in% c("north", "south")) %>%
  # Convert Joules to Megajoules
  mutate(daily_energy_MJ = daily_energy_J / 1e6) %>%
  select(-daily_energy_J)
```

# Plotting RL

```{r}
#plotting the sum!
# Ensure daily_energy_J is numeric
daily_energy_J <- daily_energy_MJ %>%
  mutate(daily_energy_J = as.numeric(daily_energy_J))

custom_palette <- c(brewer.pal(9, "Set1"), "black")

daily_RL_plot <- ggplot(daily_energy_MJ, aes(x = date, y = daily_energy_MJ, color = tree_name, shape = factor(aspect))) +
  geom_point(size = 3) +  # Use size 3 for points
  facet_wrap(~ site, scales = "free_y") +
  scale_color_manual(values = custom_palette) +  # Using custom palette with 9 colors for tree_name
  scale_shape_manual(values = c(15, 16, 17, 18, 19, 20)) +  # Define shapes for each aspect
  labs(x = "Date", y = "Daily Energy (Joules)", color = "Tree Name", shape = "Aspect") +
  theme_minimal() +
  scale_y_continuous(breaks = seq(min(daily_energy_MJ$daily_energy_J), max(daily_energy_MJ$daily_energy_J), length.out = 10))

print(daily_RL_plot)
```

```{r}
#plotting the mean!
##mean daily dataframe
mean_daily_energy_J <- all_treetemps %>%
  group_by(date, tree_name, site, aspect) %>%
  summarize(daily_energy_J = mean(energy_J, na.rm = TRUE)) %>%
  ungroup()

mean_daily_RL_plot <- ggplot(mean_daily_energy_J, aes(x = date, y = daily_energy_J, color = tree_name, shape = factor(aspect))) +
  geom_point(size = 3) +  # Use size 3 for points
  facet_wrap(~ site, scales = "free_y") +
  scale_color_manual(values = custom_palette) +  # Using custom palette with 9 colors for tree_name
  scale_shape_manual(values = c(15, 16, 17, 18, 19, 20)) +  # Define shapes for each aspect
  labs(x = "Date", y = "Daily Energy (Joules)", color = "Tree Name", shape = "Aspect") +
  theme_minimal() +
  scale_y_continuous(breaks = seq(min(daily_energy_J$daily_energy_J), max(daily_energy_J$daily_energy_J), length.out = 10))

print(daily_RL_plot)
```

```{r}
#coloring only by aspect and not doing a shape

custom_palette <- c("north" = "darkgreen", "south" = "red")

aspect_mean_daily_energy_plot <- ggplot(daily_energy_J, aes(x = date, y = daily_energy_J, color = aspect)) +
  geom_point(size = 3, alpha = 0.7) +  # Use size 3 for points
  facet_wrap(~ site, scales = "free_y") +
  scale_color_manual(values = custom_palette) +  # Using custom palette with 10 colors for aspect
  labs(x = "Date", y = "Daily Energy (Joules)", color = "Aspect") +
  ggtitle("Daily Mean Energy by Aspect and Site") +  # Add title to the plot
  theme_minimal() +
  scale_y_continuous(breaks = seq(min(daily_energy_J$daily_energy_J), max(daily_energy_J$daily_energy_J), length.out = 10))

print(aspect_mean_daily_energy_plot)
```

```{r}
#saving aspect plot
#saving combined plot
ggsave("aspect_mean_daily_energy_plot.png", plot = aspect_mean_daily_energy_plot, width = 10, height = 6, dpi = 300, bg = "white")
```

```{r}
#converting into a plotly graph and saving as an html

plotly_aspect_mean_daily_energy <- ggplotly(aspect_mean_daily_energy_plot)

plotly_aspect_mean_daily_energy

#save as a html website link
htmlwidgets::saveWidget(plotly_aspect_mean_daily_energy, "plotly_aspect_mean_daily_energy.html")
```

# Plotting RL Daily Average for sites

This is plotting the average of the north and south RL energy for each zone/site/burnstatus

```{r}
#creating daily average dataframe
average_daily_energy_by_site <- daily_energy_MJ %>%
  group_by(date, site) %>%
  summarize(average_energy_MJ = mean(daily_energy_MJ, na.rm = TRUE)) %>%
  ungroup() %>%
  #adding in columns for linetype purposes when plotting
  mutate(
    burned_status = if_else(grepl("_burned", site), "burned", "unburned"),
    zone = case_when(
      grepl("^pers", site) ~ "persistent",
      grepl("^trans", site) ~ "transitional",
      TRUE ~ NA_character_
    )
  )

##this is giving me the daily average of the north and south aspect outgoing Radiation by site (trans/pers burned/unburned), in megajoules
```

```{r}
#setting manual colors for sites
burned_colors <- c("burned" = "red3", "unburned" = "dodgerblue3")

#plotting daily average
avg_daily_energy <- ggplot(average_daily_energy_by_site, aes(x = date, y = average_energy_MJ, color = burned_status, linetype = zone)) +
  geom_line() +
  labs(title = "Average daily RLout by burn status and zone",
       x = "Date",
       y = "Average RL out (MJ)",
       color = "Burn Status",
       linetype = "Zone") +
  theme_minimal() +
  scale_color_manual(values = burned_colors)

avg_daily_energy
```

```{r}
#converting to a plotly
plotly_avg_daily_energy <- ggplotly(avg_daily_energy)

#saving ggplot
ggsave("avg_daily_energy.png", plot = avg_daily_energy, width = 10, height = 6, dpi = 300, bg = "white")

#saving plotly as html
htmlwidgets::saveWidget(plotly_avg_daily_energy, "plotly_avg_daily_energy.html")
```

The above plot looks good. Consider splitting it into a day and night plot?
