---
title: "radiation_plot_calcs"
output: html_document
date: "2024-09-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lterdatasampler)
library(dplyr)
library(ggplot2)
library(readr)
library(readxl)
library(lubridate)
library(plotly)
library(openxlsx)
library(plotly)
library(rstatix)
library(htmlwidgets)
library(RColorBrewer)
library(patchwork)
library(hms)
library(ggpubr)
#package for scientific notation of numbers
library(scales)

setwd("/Volumes/wcnr-network/Research/Kampf/Private/field_data")
```

## Calling in Data

```{r}
transb_energytree_table <- read_csv("nsf/drone_imagery/trans_b_energytree_table.csv") %>%
  mutate(zone = "transitional") %>%
  rename(burn_status = burn_status) %>%
  #adding a tree_id column
  mutate(tree_id = row_number()) %>%
  #selecting columns I want
  select(tree_id, zone, burn_status, lat, long)

transb_wx_15min <- read_csv("nsf/trans_burned/trans_burned_wx_15min_r.csv") %>%
  mutate(datetime = as.POSIXct(datetime, format=("%Y-%m-%d %H:%M:%S")), datetime = force_tz(datetime, tz = 'MST'))

#tree sensor temps
avg_dt_transb_treeLW <- read_csv("nsf/105E_trans_burned/day_avg_filtered_treeLWout_data_gbdbub.csv") %>%
  #filtering out only the burned data, daytime data, & transitional zone
  filter(zone == "transitional", phase == "day") %>%
  filter(burn_status != "unburned") %>%
  #renaming MJ/day column to match weather data
  rename(tree_LWout_MJd = tree_LWout_MJperd) %>%
  #removing double ID first column that appeared for some reason?
  select(-1)
```

## Filtering Data

```{r}
filtered_transb_rad_wx <- transb_wx_15min %>%
  filter(datetime >= as.POSIXct("2024-02-02 00:00:00") & datetime <= as.POSIXct("2024-05-25 00:00:00")) %>%
   # Adding in date, time, and phase columns
  mutate(
    date = as.Date(datetime),
    time = format(datetime, "%H:%M:%S"),
    time_hms = hms::as_hms(time),  # Convert to hms object for phase calculation
    phase = case_when(
      time_hms >= hms::as_hms("08:00:00") & time_hms < hms::as_hms("17:00:00") ~ "day",
      time_hms < hms::as_hms("08:00:00") | time_hms >= hms::as_hms("17:00:00") ~ "night",
      TRUE ~ NA_character_)) %>%
      select(datetime, date, time, phase, SnowDepth_m, AirTC_Avg, SWin_Avg, SWout_Avg, SWalbedo_Avg, LWin_Avg, LWout_Avg, SWnet_Avg, LWnet_Avg, NR_Avg)
```

## Data Wrangling

Creating a daily average wx station dataframe, then converting to MJ/day

```{r}
#calculations for radiation conversions from W/m2 to MJ/day
## create a daily average dataframe
avg_dt_transb_rad_wx<- filtered_transb_rad_wx %>%
  group_by(date, phase) %>%
  summarize(across(everything(), mean, na.rm = TRUE)) %>%
  select(-c(datetime, time)) %>%
  group_by(date, phase) %>%
  # Convert mean radiation to MJ/day - assuming constent for m2 value
  mutate(SWin_MJd = (SWin_Avg/ 1e6) * 86400, SWout_MJd = (SWout_Avg/ 1e6) * 86400, LWin_MJd = (LWin_Avg/ 1e6) * 86400, LWout_MJd = (LWout_Avg/ 1e6) * 86400, SWnet_MJd = (SWnet_Avg / 1e6) * 86400, LWnet_MJd = (LWnet_Avg/ 1e6) * 86400, NR_MJd = (NR_Avg / 1e6) * 86400) %>%
  rename(SWin_wperm2 = SWin_Avg, SWout_wperm2 = SWout_Avg, SWnet_wperm2 = SWnet_Avg, LWin_wperm2 = LWin_Avg, LWout_wperm2 = LWout_Avg, LWnet_wperm2 = LWnet_Avg, NR_wperm2 = NR_Avg) %>%
  mutate(zone = "transitional", burn_status = "burned") %>%
  #filtering out only daytime values
  filter(phase == "day") %>%
  #reordering so the like values are next to each other
  select(date, phase, zone, burn_status, SnowDepth_m, AirTC_Avg, SWin_wperm2, SWin_MJd, SWout_wperm2, SWout_MJd, SWnet_wperm2, SWnet_MJd, SWalbedo_Avg, LWin_wperm2, LWin_MJd, LWout_wperm2, LWout_MJd, LWnet_wperm2, LWnet_MJd, NR_wperm2, NR_MJd) %>%
  #setting decimal number
   mutate(across(SnowDepth_m:last_col(), ~ round(., 4)))
```

Combining data into one dataframe

```{r}
transb_comb_radtree_data <- avg_dt_transb_rad_wx %>%
  full_join(avg_dt_transb_treeLW)
```

## Plotting

```{r}
color_values_MJd <- c(
  "SWin_MJd" = "#D95F02",
  "SWout_MJd" = "#E6AB02",
  "LWout_MJd" = "#66A61E",
  "LWin_MJd" = "#2e5e39",
  "tree_LWout_MJd" = "#7570B3")

color_values_wperm2 <- c(
  "SWin_wperm2" = "#D95F02",
  "SWout_wperm2" = "#E6AB02",
  "LWout_wperm2" = "#66A61E",
  "LWin_wperm2" = "#2e5e39",
  "tree_LWout_wperm2" = "#7570B3")



# Define line types
line_types <- c(
  "Weather Station" = "solid",
  "Tree Temperature Sensors" = "dashed"
)

#changing labels of values in plots for the legend
color_labels <- c(
  "SWin_Avg" = "Shortwave In (Avg)",
  "SWout_Avg" = "Shortwave Out (Avg)",
  "LWin_Avg" = "Longwave In (Avg)",
  "LWout_Avg" = "Longwave Out (Avg)",
  "tree_LWout_avg_wperm2" = "Tree LW Out (Avg)"  # New label for the specific line
)
```

```{r}
#MJ/day plot
combined_day_rad_wx_plot_MJd <- ggplot(data = transb_comb_radtree_data) + 
  geom_line(aes(x = date, y = SWin_MJd, color = "SWin_MJd", linetype = "Weather Station"), linewidth = 0.6, alpha = 0.9) +
  geom_line(aes(x = date, y = SWout_MJd, color = "SWout_MJd", linetype = "Weather Station"), linewidth = 0.6, alpha = 0.8) +
  geom_line(aes(x = date, y = LWin_MJd, color = "LWin_MJd", linetype = "Weather Station"), linewidth = 0.7, alpha = 0.9) +
  geom_line(aes(x = date, y = LWout_MJd, color = "LWout_MJd", linetype = "Weather Station"), linewidth = 0.7) +
  geom_line(aes(x = date, y = tree_LWout_MJ, color = "tree_LWout_MJ", linetype = "Tree Temperature Sensors")) +
  facet_wrap(~ zone + burn_status, scales = "free_y", dir = "h") +  # Facet by zone and phase
  labs(
    #title = "Transitional Unburned",
    x = "Date",
    y = "Radiation components (MJ/day)",
    color = "Variable", 
    linetype = "Data Source"
    ) +
  theme_bw() +  # Use a minimal theme for a clean look
  scale_color_manual(values = color_values_MJd, labels = color_labels) + 
  scale_linetype_manual(values = line_types)

combined_day_rad_wx_plot_MJd
```

```{r}
#W/m2 plot
combined_day_rad_wx_plot_Wperm2 <- ggplot(data = transb_comb_radtree_data) + 
  geom_line(aes(x = date, y = SWin_wperm2, color = "SWin_wperm2", linetype = "Weather Station"), linewidth = 0.6, alpha = 0.9) +
  geom_line(aes(x = date, y = SWout_wperm2, color = "SWout_wperm2", linetype = "Weather Station"), linewidth = 0.6, alpha = 0.8) +
  geom_line(aes(x = date, y = LWin_wperm2, color = "LWin_wperm2", linetype = "Weather Station"), linewidth = 0.7, alpha = 0.9) +
  geom_line(aes(x = date, y = LWout_wperm2, color = "LWout_wperm2", linetype = "Weather Station"), linewidth = 0.7) +
  geom_line(aes(x = date, y = tree_LWout_wperm2, color = "tree_LWout_wperm2", linetype = "Tree Temperature Sensors")) +
  facet_wrap(~ zone + burn_status, scales = "free_y", dir = "h") +  # Facet by zone and phase
  labs(
    #title = "Transitional Unburned",
    x = "Date",
    y = "Radiation components (W/m2)",
    color = "Variable", 
    linetype = "Data Source"
    ) +
  theme_bw() +  # Use a minimal theme for a clean look
  scale_color_manual(values = color_values_wperm2, labels = color_labels) + 
  scale_linetype_manual(values = line_types)

combined_day_rad_wx_plot_Wperm2
```

\*\*there is something wrong with the way I am converting the tree_LWout to MJ/day, as the

Plotting net SW and LW to see if this matched wyatts data?

```{r}
netrad_plot <- ggplot(data = transb_comb_radtree_data) +
  geom_col(aes(x = date, y = SWnet_wperm2, fill = "SWnet_wperm2"), position = "stack") +
  geom_col(aes(x = date, y = LWnet_wperm2, fill = "LWnet_wperm2"), position = "stack") +
   labs(x = "Date", y = "Net Radiation (W/m²)", fill = "Radiation Type") +
  scale_fill_manual(values = c("SWnet_wperm2" = "orange", "LWnet_wperm2" = "blue")) +  # Custom colors
  theme_bw()

netrad_plot
```

\*creating a bar plot for radiation and a
