---
title: "wx_datawrangling"
output: html_document
date: "2024-08-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Set up

```{r}
library(tidyverse)
library(lterdatasampler)
library(dplyr)
library(ggplot2)
library(readr)
library(readxl)
library(lubridate)
library(plotly)
library(openxlsx)
library(plotly)
library(rstatix)
library(htmlwidgets)
library(RColorBrewer)
library(patchwork)

setwd("/Volumes/wcnr-network/Research/Kampf/Private/field_data")
```

# Calling in Wx Data

```{r}
#trans_burned 15-minute data

transb_wx_15min <- read_excel('nsf/trans_burned/trans_burned_wx_15min.xlsx')

#fix datetime issue, use as.POSIXct instead of ymd_hms
transb_wx_15min_r <- transb_wx_15min %>%
  mutate(datetime = as.POSIXct(datetime, format=("%Y-%m-%d %H:%M:%S")),
         #forcing the timezone to me MST, otherwise it is being recognized as UTC
         dt_mst = force_tz(datetime, tz = 'MST')) 

transb_wx_15min_r <- transb_wx_15min_r %>%
  #select dt_mst column and remove the old datetime column, then rename dt_mst
  select(-datetime) %>%
  rename(datetime = dt_mst) %>%
  select(datetime, RECORD, Batt_volt, SnowDepth_m, AirTC_Avg, WS_ms_Avg, WindDir, RH, SWin_Avg, SWout_Avg, SWalbedo_Avg, LWin_Avg, LWout_Avg, SWnet_Avg, LWnet_Avg, NR_Avg, everything())

#writing the 15min trans_b weather to the n-drive
write.xlsx(transb_wx_15min_r, "nsf/trans_burned/trans_burned_wx_15min_r.xlsx")
```

```{r}
#trans_unburned data

transub_wx_5min <- read_excel("nsf/trans_unburned/trans_ub_wx_5min.xlsx")

transub_wx_15min_r <- transub_wx_5min %>%
  #convert 5 min timestep to 15 minute timestep
  #ensuring datetime is MST and recognized
  mutate(datetime = TIMESTAMP) %>%
  mutate(datetime = as.POSIXct(datetime, format=("%Y-%m-%d %H:%M:%S")),
          #forcing the timezone to me MST, otherwise it is being recognized as UTC
         datetime = force_tz(datetime, tz = 'MST')) %>%
# Create a new column for 15-minute intervals
  mutate(interval = floor_date(datetime, unit = "15 minutes")) %>%
  # Group by the 15-minute interval
  group_by(interval) %>%
  # Calculate the mean for all other columns
summarize(across(where(is.numeric), mean, na.rm = TRUE), .groups = 'drop') %>%  # Rename 'interval' to 'datetime' and remove the original 'datetime' column
  rename(datetime = interval) %>%
  rename(Batt_volt = BattV_Avg) %>%
  rename(AirTC_Avg = AirTemp_Avg) %>%
  rename(RH = RH_Avg) %>%
  rename(WS_ms_Avg = WindSpeed) %>%
  rename(SnowDepth_m = SnowDepth_Avg) %>%
  select(datetime, RECORD, Batt_volt, SnowDepth_m, AirTC_Avg, WS_ms_Avg, WindDir, RH, SWin_Avg, SWout_Avg, SWalbedo_Avg, LWin_Avg, LWout_Avg, SWnet_Avg, LWnet_Avg, NR_Avg, everything())

#writing the 15min trans_ub weather to the n-drive
write.xlsx(transub_wx_15min_r, "nsf/trans_unburned/trans_unburned_wx_15min_r.xlsx")
```

```{r}
#persistent burned wx data

persb_wx_15min <- read_excel("nsf/pers_burned/pers_burned_wx_15min_composite.xlsx")

#making sure the datetime column is set to MST and the correct format
persb_wx_15min_r <- persb_wx_15min %>%
  mutate(datetime = as.POSIXct(TIMESTAMP, format=("%Y-%m-%d %H:%M:%S"), tz="MST")) %>%
  select(datetime, everything()) %>%
  rename(TIMESTAMP_UTC = TIMESTAMP)

#renaming the columns to match other weather station data and creating a correct snow depth column
persb_wx_15min_r <- persb_wx_15min_r %>%
  rename(Batt_volt = BattV_Min) %>%
  #timestamp column is UTC time
  rename(SnowDepth_m = DBTCDT_Avg) %>%
  #applying offset to snow depth column for the pers_burned zone
  mutate(SnowDepth_m = (SnowDepth_m-0.03)) %>%
  select(datetime, RECORD, Batt_volt, SnowDepth_m, AirTC_Avg, WS_ms_Avg, WindDir, RH, SWin_Avg, SWout_Avg, SWalbedo_Avg, LWin_Avg, LWout_Avg, SWnet_Avg, LWnet_Avg, NR_Avg, everything())

write.xlsx(persb_wx_15min_r, "nsf/pers_burned/pers_burned_wx_15min_r.xlsx")
```

```{r}
#persistent_unburned data
persub_wx_15min <- read_excel("nsf/pers_unburned/pers_unburned_wx_15min_composite.xlsx")

persub_wx_15min_r <- persub_wx_15min %>%
  mutate(datetime = as.POSIXct(TIMESTAMP, format=("%Y-%m-%d %H:%M:%S"), tz="MST")) %>%
  select(datetime, everything()) %>%
  rename(TIMESTAMP_UTC = TIMESTAMP)

#renaming the columns to match other weather station data and creating a correct snow depth column
persub_wx_15min_r <- persub_wx_15min_r %>%
  rename(Batt_volt = BattV_Min) %>%
  #timestamp column is UTC time
  rename(SnowDepth_m = DBTCDT_Avg) %>%
  mutate(RH = (RH_Min + RH_Max) / 2) %>%
#no offset applied to the snowDepth column, as Dan did not specify that the unburned zone needed it
  select(datetime, RECORD, Batt_volt, SnowDepth_m, AirTC_Avg, WS_ms_Avg, WindDir, RH, SWin_Avg, SWout_Avg, SWalbedo_Avg, LWin_Avg, LWout_Avg, SWnet_Avg, LWnet_Avg, NR_Avg, everything())

write.xlsx(persub_wx_15min_r, "nsf/pers_unburned/pers_unburned_wx_15min_r.xlsx")
```

```{r}
#persistent_burned - hourly data

persb_wx_hourly <- read_csv("nsf/pers_burned/pers_burned_wx_hourly_composite.csv")

#making sure the datetime column is set to MST and the correct format
persb_wx_hourly_r <- persb_wx_hourly %>%
  mutate(datetime = as.POSIXct(TIMESTAMP, format=("%Y-%m-%d %H:%M:%S"), tz="MST")) %>%
  select(datetime, everything()) %>%
  rename(TIMESTAMP_UTC = TIMESTAMP)

#renaming the columns to match other weather station data and creating a correct snow depth column
persb_wx_hourly_r <- persb_wx_hourly_r %>%
  rename(Batt_volt = BattV_Min) %>%
  #timestamp column is UTC time
  rename(SnowDepth_m = DBTCDT_Avg) %>%
  #applying offset to snow depth column for the pers_burned zone
  mutate(SnowDepth_m = (SnowDepth_m-0.03)) %>%
  select(datetime, RECORD, Batt_volt, SnowDepth_m, AirTC_Avg, WS_ms_Avg, WindDir, RH, SWin_Avg, SWout_Avg, SWalbedo_Avg, LWin_Avg, LWout_Avg, SWnet_Avg, LWnet_Avg, NR_Avg, everything())

write_csv(persb_wx_hourly_r, "nsf/pers_burned/pers_burned_wx_hourly_r.csv")
```

```{r}
#persistent_unburned - hourly data

persub_wx_hourly <- read_csv("nsf/pers_unburned/pers_unburned_wx_hourly_composite.csv")

#making sure the datetime column is set to MST and the correct format
persub_wx_hourly_r <- persub_wx_hourly %>%
  mutate(datetime = as.POSIXct(TIMESTAMP, format=("%Y-%m-%d %H:%M:%S"), tz="MST")) %>%
  select(datetime, everything()) %>%
  rename(TIMESTAMP_UTC = TIMESTAMP)

#renaming the columns to match other weather station data and creating a correct snow depth column
persub_wx_hourly_r <- persub_wx_hourly_r %>%
  rename(Batt_volt = BattV_Min) %>%
  #timestamp column is UTC time
  rename(SnowDepth_m = DBTCDT_Avg) %>%
#did not apply an offset for the snow depth column for the unburned site
  select(datetime, RECORD, Batt_volt, SnowDepth_m, AirTC_Avg, WS_ms_Avg, WindDir, RH, SWin_Avg, SWout_Avg, SWalbedo_Avg, LWin_Avg, LWout_Avg, SWnet_Avg, LWnet_Avg, NR_Avg, everything())

write_csv(persub_wx_hourly_r, "nsf/pers_unburned/pers_unburned_wx_hourly_r.csv")
```
